apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-discord-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Mi
