# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  clean:
    runs-on: self-hosted
    steps:
      - name: Clean Directory
        run: |
          sudo systemctl stop discordbot.service
          sudo rm -rf __pycache__

  build:
    runs-on: self-hosted
    needs: [clean]
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo python3 -m pip install --upgrade pip
        (test -d env && rm -rf env)
        source ./env/bin/activate
        pip3 install flake8 pytest
        if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
        
  deploy:
    runs-on: self-hosted
    needs: [build]
    steps:
      - name: setup_env_vars
        run: |
          echo "${{ secrets.TOKEN }}" > .env
          echo "${{ secrets.DB_HOST }}" >> .env
          echo "${{ secrets.DB_USER }}" >> .env
          echo "${{ secrets.DB_PASS }}" >> .env
          echo "${{ secrets.DB_NAME_SUBMISSIONS }}" >> .env
          echo "${{ secrets.DB_NAME_PLAYERS }}" >> .env
          echo "${{ secrets.SUBMIT_RECIPIENT }}" >> .env
          echo "${{ secrets.DISCORD_BOT_ID }}" >> .env
          
      - name: run_bot
        run: |
          sudo systemctl start discordbot.service
